### ISSUE TITLE
db

### ISSUE THREAD

**Issue by chenming7583** [linking12/saluki#3]
能补充个建表语句 跑起来学习学习 看代码 一下还是有点空洞

**Comment by linking12** [comment]
你是看网关还是服务注册与发现？网关的话是jpa的，可以自动生成表结构，而服务注册与发现不需要表结构

**Comment by linking12** [comment]
@chenming7583 你可以加下我的微信：linking12，我也想详细了解一下，对于使用grpc做服务化，一般会碰到什么问题
